[tool.black]
line-length = 88
target-version = ["py311"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
strict_optional = true

[[tool.mypy.overrides]]
module = "tests.*"
disallow_untyped_defs = false
disallow_incomplete_defs = false

[tool.pytest.ini_options]
testpaths = ["app/tests"]
python_files = "test_*.py"
python_functions = "test_*"
python_classes = "Test*"

[tool.bandit]
exclude_dirs = ["tests", "venv"]
skips = ["B101"]

[tool.ruff]
# Basic configuration
line-length = 88
target-version = "py311"
required-version = ">=0.9.0"

# Rule selection
select = ["E", "F", "I", "C4", "B", "UP"]
ignore = []

# Formatter configuration
format.quote-style = "double"
format.indent-style = "space"
format.line-ending = "auto"
format.skip-magic-trailing-comma = false

# isort configuration
isort.known-third-party = ["fastapi", "pydantic", "sqlalchemy"]
